### ISSUE TITLE
npm package not updated with fix

### ISSUE THREAD

**Issue by nineten** [matteocontrini/node-periscope-stream#2]
Hey thank you for the great post on periscope, was very helpful to a side project I'm looking into.

With regards to https://github.com/matteocontrini/node-periscope-stream/commit/36f045349e8a0cdd54e61b1d760c34253ad6dc74
I've noticed the typo has been fixed, but the npm package is still without the fix.
Have you republished the package yet?

**Comment by nineten** [comment]
Ah I didn't notice that periscope has changed their api (since it isn't public) and this isn't working anymore.

**Comment by matteocontrini** [comment]
[Released](https://github.com/matteocontrini/node-periscope-stream/releases/tag/v0.1.5).
Thank you!
