### ISSUE TITLE
 Refusing to install node-periscope-stream as a dependency of itself

### ISSUE THREAD

**Issue by hendisantika** [matteocontrini/node-periscope-stream#5]
hendisantika@NamikazeMinato:~/periscope/node-periscope-stream$ npm install node-periscope-stream
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-periscope-stream"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install node-periscope-stream as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hendisantika/periscope/node-periscope-stream/npm-debug.log
hendisantika@NamikazeMinato:~/periscope/node-periscope-stream$

**Comment by matteocontrini** [comment]
Wrong npm usage, cd to `~/periscope` and `npm install node-periscope-stream --save`

**Comment by hendisantika** [comment]
How can I test this is works?
