### ISSUE TITLE
Periscope API

### ISSUE THREAD

**Issue by hendisantika** [matteocontrini/node-periscope-stream#6]
Hi Matteo,

I want to ask you, Periscope API still opened till now?
Because I can not test your periscope.js in this repo?

Could you please guide me to run your periscope.js so that I can see it is works.

Thanks

**Comment by matteocontrini** [comment]
Instructions are in the README, and if you need to learn how to use Node.js modules, there's the [documentation](https://nodejs.org/api/modules.html) for that
